# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('url', models.TextField()),
                ('paper', models.TextField()),
                ('author', models.TextField()),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
