# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=100)),
                ('articleID', models.TextField()),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('articleID', models.TextField()),
                ('userID', models.TextField()),
                ('date', models.DateField(default=b'2018-01-10')),
                ('time', models.TimeField(default=b'18:19:25')),
            ],
            options={
                'ordering': ('text',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.TextField()),
                ('password', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(max_length=100)),
                ('frequency', models.IntegerField(default=0)),
                ('userID', models.TextField()),
            ],
            options={
                'ordering': ('tag',),
            },
        ),
        migrations.DeleteModel(
            name='Derrick',
        ),
        migrations.AddField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=b'18:19:25'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=b'2018-01-10'),
        ),
    ]
