# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-12 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20180110_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date',
            field=models.DateField(default=b'2018-01-12'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=b'11:18:09'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=b'2018-01-12'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=b'11:18:09'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='language',
            field=models.CharField(default='python', max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='style',
            field=models.CharField(default='friendly', max_length=100),
        ),
    ]
