# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0007_auto_20180115_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eduLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=b'14:13:57'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=b'14:13:57'),
        ),
    ]
