# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0008_auto_20180115_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=b'14:27:19'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=b'14:27:19'),
        ),
    ]
