# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0011_auto_20180208_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='time',
            field=models.TimeField(default=b'14:44:47'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default=b'14:44:47'),
        ),
    ]
